apiVersion: v1
kind: ConfigMap
metadata:
  name: github-runner-config
  namespace: default
data:
  RUNNER_URL: "https://github.com/my-org/my-repo"
  RUNNER_NAME_PREFIX: "k8s-runner-"
  RUNNER_LABELS: "kubernetes,self-hosted"
  RUNNER_GROUP: "Default"
  ACTIONS_RESULTS_URL: ""
  DISABLE_AUTO_UPDATE: "false"
